version: "3"

services:
  mailhog:
    image: "mailhog/mailhog"
    container_name: "mailhog"
    hostname: "mailhog"
    restart: always
    volumes:
      - "$HOME/data/mailhog:/home/mailhog"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailhog.rule=Host(`mailhog.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.mailhog.entrypoints=https"
      - "traefik.http.routers.mailhog.tls=true"
      - "traefik.http.routers.mailhog.tls.certresolver=cloudflare"
      - "traefik.http.routers.mailhog.service=mailhog"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"

      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  proxy:
    external: true
