version: "3"

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: "code-server"
    restart: always
    volumes:
      - "$HOME/data/code-server/config:/config"
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - PASSWORD=${PASSWORD}
      #- HASHED_PASSWORD=${HASHED_PASSWORD}
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      #- SUDO_PASSWORD_HASH=${SUDO_PASSWORD_HASH}
      - PROXY_DOMAIN=`code.${TRAEFIK_DOMAIN}`
      - DEFAULT_WORKSPACE=/config/workspace
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.codeserver.rule=Host(`code.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.codeserver.entrypoints=https"
      - "traefik.http.routers.codeserver.tls=true"
      - "traefik.http.routers.codeserver.tls.certresolver=cloudflare"

      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  proxy:
    external: true
