version: '3'

services:
  mailhog:
    image: "synapse-admin-ui:latest"
    container_name: "synapse-admin-ui"
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.synapse-admin-ui.rule=Host(`synapse-admin.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.synapse-admin-ui.entrypoints=https"
      - "traefik.http.routers.synapse-admin-ui.tls=true"
      - "traefik.http.routers.synapse-admin-ui.tls.certresolver=cloudflare"
      - "traefik.http.routers.synapse-admin-ui.service: 'synapse-admin-ui"
      - "traefik.http.services.synapse-admin-ui.loadbalancer.server.port: '80"

      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  proxy:
    external: true