version: '3'

services:
  mailhog:
    image: "synapse-admin-ui:latest"
    container_name: "synapse-admin-ui"
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.synapseadminui.rule=Host(`synapseadmin.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.synapseadminui.entrypoints=https"
      - "traefik.http.routers.synapseadminui.tls=true"
      - "traefik.http.routers.synapseadminui.tls.certresolver=cloudflare"
      - "traefik.http.routers.synapseadminui.service: 'synapseadminui"
      - "traefik.http.services.synapseadminui.loadbalancer.server.port: '80"

      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  proxy:
    external: true