version: "3"

services:
  gotify:
    image: gotify/server
    container_name: gotify
    restart: unless-stopped
    volumes:
      - "$HOME/data/gotify/data:/app/data"
    environment:
      - GOTIFY_DEFAULTUSER_PASS=${GOTIFY_DEFAULTUSER_PASS}
    networks:
      - proxy
    labels:
      # Enable Autohehaling, Metrics and Traefik
      - "autoheal.enable=true"
      - "autoheal.stop.timeout=10"
      - "metrics.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.gotify.rule=Host(`gotify.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.gotify.entrypoints=https"
      - "traefik.http.routers.gotify.tls=true"
      - "traefik.http.routers.gotify.tls.certresolver=cloudflare"

      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    external: true
