version: '3.3'
services:
  x-ui:
    networks:
      - proxy
    volumes:
      - "$HOME/data/x-ui/db/:/etc/x-ui/"
      - "$HOME/data/x-ui/cert/:/root/cert/"
    container_name: x-ui
    restart: unless-stopped
    image: 'enwaiax/x-ui:latest'

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xui.rule=Host(`shadow.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.xui.entrypoints=https"
      - "traefik.http.routers.xui.tls=true"
      - "traefik.http.routers.xui.tls.certresolver=cloudflare"

      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  proxy:
    external: true
