version: "3"

services:
  x-ui:
    image: x-ui:latest
    container_name: "x-ui"
    restart: always
    volumes:
      - "$HOME/data/x-ui/db/:/etc/x-ui/"
      - "$HOME/data/x-ui/cert/:/root/cert/"
    entrypoint: ./x-ui
    networks:
      - proxy
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.xui.rule=Host(`shadow.${TRAEFIK_DOMAIN}`)"
    #   - "traefik.http.routers.xui.entrypoints=https"
    #   - "traefik.http.routers.xui.tls=true"
    #   - "traefik.http.routers.xui.tls.certresolver=cloudflare"

    #   # Watchtower Update
    #   - "com.centurylinklabs.watchtower.enable=true"
networks:
  proxy:
    external: true
