version: "3"

services:
  web:
    image: "traefik:latest"
    hostname: "traefik.${DOMAIN}"
    restart: always
    depends_on:
      - socket-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./traefik.yml:/traefik.yml:ro"
      - "./rules:/etc/traefik/rules:ro"
      - "./letsencrypt:/letsencrypt"
    environment:
      - TZ=${TZ}
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    networks:
      - proxy
    labels:
      # Enable Autohehaling, Metrics and Traefik
      - "autoheal.enable=true"
      - "autoheal.stop.timeout=10"
      - "metrics.enable=true"
      - "traefik.enable=true"

      # Traefik dashboard
      - "traefik.http.routers.base-traefik.entrypoints=https"
      - "traefik.http.routers.base-traefik.middlewares=admin-auth@file"
      - "traefik.http.routers.base-traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.base-traefik.tls=true"
      - "traefik.http.routers.base-traefik.tls.certresolver=cloudflare"
      - "traefik.http.routers.base-traefik.service=api@internal"

      # Traefik exporter
      - "traefik.http.routers.base-traefik-exporter.middlewares=admin-auth@file"
      - "traefik.http.routers.base-traefik-exporter.entrypoints=https"
      - "traefik.http.routers.base-traefik-exporter.rule=Host(`traefik.${DOMAIN}`) && Path(`/traefik/metrics`)"
      - "traefik.http.routers.base-traefik-exporter.tls=true"
      - "traefik.http.routers.base-traefik-exporter.tls.certresolver=cloudflare"
      - "traefik.http.routers.base-traefik-exporter.service=prometheus@internal"

      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"

  socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: traefik-socket-proxy
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
    networks:
      - proxy
    labels:
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    external: true
