################################################################
# Entrypoints configuration
################################################################
entryPoints:
  http:
    address: ":80"

  https:
    address: ":443"

################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false

  file:
    directory: /etc/traefik/dynamic
    watch: true

################################################################
# API and dashboard configuration
################################################################
api:
  insecure: false
  dashboard: true

################################################################
# Let’s encrypt configuration
################################################################
certificatesResolvers:
  cloudflare:
    acme:
      email: info@mitra.cloud
      storage: ./letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare

################################################################
# Ping configuration
################################################################
ping:
  entryPoint: traefik

################################################################
# Retry sending request if network error
################################################################
retry:
  attempts: 3

################################################################
# Enable prometheus metrics
################################################################
metrics:
  prometheus: {}

log:
  level: INFO
