version: "3.7"
services:
  web:
    image: "gitlab/gitlab-ce:latest"
    restart: always
    hostname: "gitlab.${TRAEFIK_DOMAIN}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://gitlab.${TRAEFIK_DOMAIN}"
        # Add any other gitlab.rb configuration here, each on its own line
    volumes:
      - "$HOME/data/gitlab/config:/etc/gitlab"
      - "$HOME/data/gitlab/logs:/var/log/gitlab"
      - "$HOME/data/gitlab/data:/var/opt/gitlab"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.gitlab.entrypoints=https"
      - "traefik.http.routers.gitlab.tls=true"
      - "traefik.http.routers.gitlab.tls.certresolver=cloudflare"

      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"

    shm_size: "256m"

    networks:
      - proxy

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: always
    depends_on:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "$HOME/data/gitlab/gitlab-runner:/etc/gitlab-runner"
    networks:
      - proxy
networks:
  proxy:
    external: true
