version: "3.6"
services:
  web:
    image: "gitlab/gitlab-ee:latest"
    restart: always
    hostname: "gitlab.${TRAEFIK_DOMAIN}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url `https://gitlab.${TRAEFIK_DOMAIN}`
        # Add any other gitlab.rb configuration here, each on its own line
    volumes:
      - "$HOME/data/gitlab/config:/etc/gitlab"
      - "$HOME/data/gitlab/logs:/var/log/gitlab"
      - "$HOME/data/gitlab/data:/var/opt/gitlab"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.gitlab.entrypoints=https"
      - "traefik.http.routers.gitlab.tls=true"
      - "traefik.http.routers.gitlab.tls.certresolver=cloudflare"

      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"

    shm_size: "256m"
