version: "3"

services:
  autoheal:
    image: willfarrell/autoheal
    hostname: "autoheal.${DOMAIN}"
    network_mode: none
    restart: always

    environment:
      - TZ=Europe/Istanbul
      - AUTOHEAL_CONTAINER_LABEL=autoheal.enable
      - AUTOHEAL_INTERVAL=60
      - AUTOHEAL_START_PERIOD=0
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10

    labels:
      metrics.enable: "true"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
